name: employee_ledger
description: "A new Flutter project to manage employee records and ledger."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  path_provider: ^2.1.5
  equatable: ^2.0.7
  intl: ^0.20.2
  sembast: ^3.8.4+1
  path: ^1.9.1
  sembast_web: '2.4.1'
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^2.5.7
  freezed_annotation: ^2.2.0
  test: ^1.25.15
  
 

  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mockito: ^5.4.5

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  ios: true
  web: true
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
